[package]
name = "the_net"
version = "0.1.0"
authors = ["xipi2048 <raen@quantumtrip.org>"]
edition = "2018"

[dependencies]
# game framework: https://github.com/ryanisaacg/quicksilver
quicksilver = "0.4"
mergui = { git="https://github.com/lenscas/mergui" }